# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
      env: 
        NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        CALENDAR_SERVICE: ${{ secrets.CALENDAR_SERVICE }}
        CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
        OWNER_1: ${{ secrets.OWNER_1 }}
        OWNER_2: ${{ secrets.OWNER_2 }}
        OWNER_3: ${{ secrets.OWNER_3 }}
        OWNER_4: ${{ secrets.OWNER_4 }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
    - run: npm test
